# Generated by Django 5.0.2 on 2024-02-28 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosiapp', '0004_mmesage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MMesage',
            new_name='Mesage',
        ),
    ]
