# Generated by Django 5.0.2 on 2024-02-28 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hosiapp', '0005_rename_mmesage_mesage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesage',
            new_name='Message',
        ),
    ]
