# Generated by Django 5.0.2 on 2024-02-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hosiapp', '0006_rename_mesage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='allan', max_length=200),
            preserve_default=False,
        ),
    ]
